/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rubilnik;

import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.springframework.boot.SpringApplication;

import com.fasterxml.jackson.databind.ObjectMapper;

public class App {
    static ObjectMapper objectMapper = new ObjectMapper();
    static SessionFactory sessionFactory = new Configuration().configure().buildSessionFactory();

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        SpringApplication.run(Controller_Test.class, args);
    }
}