/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rubilnik;

import org.springframework.boot.SpringApplication;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        SpringApplication.run(Controller_REST_Test.class, args);
    }
}
